config/routes.rb
Bandleader::Application.routes.draw do
 
   
  resources :sessions
  resources :connections
  resources :votes		
  resources :users
  resources :stations
  
  
  resources :posts
  root to: 'static_pages#home' 
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about' 	
  match '/contact', to: 'static_pages#contact'
  match '/connect', to: 'static_pages#connect' 
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'songs/:id', :to => 'songs#destroy'
  get 'songs/:id', :to => 'songs#show'

  match 'upload' => 'songs#upload', :as => :upload
  match 'songs#create' => 'songs#upload', :as => :upload
  match 'songs' => 'songs#upload', :as => :upload
  match 'station_next#id' => 'stations#next_song', :as => :next_song
  resources :songs
  get 'connect', to: 'connections#create', as: 'connect'
  get 'disconnect', to: 'connections#destroy', as: 'disconnect'
		
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
 		 @home_page = true
	end
	
	def help
	end

	def about
	end
	
	def contact
	end
	
	def connect
	end
	
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Contract') %> 
<h1>About Bandleader </h1> 
<p> 
	<section> 
	Under Construction
	Bandleader is an application to create, share, and collaborate on playlists. 
	</section> 
</p> 

app/views/static_pages/connect.html.erb
<%= link_to "Join", stations_url %> 
<%= link_to "Create", new_station_url %> 

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contract') %> 
<h1>Contact </h1> 
<p> 
	<section> 
<p> 
	Under Construction
</p> 

	</section>
	
</p> 

app/views/static_pages/help.html.erb
<% provide(:title, 'Contract') %> 
<h1>Help </h1> 
<p> 
	Under Construction
</p> 

app/views/static_pages/home.html.erb
<% provide(:title, 'Contract') %> 
<div class="center hero-unit">
		<div id="front-main">
		  <h1>Welcome to bandleader</h1>
		  <h2>
		    Create, share, and collaborate on music playlists with your friends.
		  </h2>
		  <!--<%= link_to "Sign up!", signup_path, class: "btn btn-large btn-primary" %>-->
		</div>
		<div id="front-side-bar">
		<%= form_tag sessions_path, :class => "front-signin" do %>
			<%=   text_field_tag :username, params[:username] , "size" => 20 , :placeholder => "username"  %>
			<%=  password_field_tag :password, params[:password], "size" => 20, :placeholder => "password" %>
		  <%= submit_tag 'sign in', class: "btn btn-large btn-primary"%>
		<% end %>
		<%= form_tag "/signup", :class => "front-signup" do %>
			<%= text_field "person", "name", "size" => 20 , :placeholder => "username" %>
			<%= text_field "person", "name", "size" => 20 , :placeholder =>  "email" %>
		  <%= text_field "person", "name", "size" => 20 , :placeholder => "password" %>
		  <%= submit_tag 'Sign up for bandleader', class: "btn btn-large btn-primary"%>
		<% end %>
		</div>
</div>
	<div id="front-bottom">
		 
		  </div>