config/routes.rb
Bandleader::Application.routes.draw do
 
   
  resources :sessions
  resources :connections
  resources :votes		
  resources :users
  resources :stations
  
  
  resources :posts
  root to: 'static_pages#home' 
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about' 	
  match '/contact', to: 'static_pages#contact'
  match '/connect', to: 'static_pages#connect' 
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'songs/:id', :to => 'songs#destroy'
  get 'songs/:id', :to => 'songs#show'

  match 'upload' => 'songs#upload', :as => :upload
  match 'songs#create' => 'songs#upload', :as => :upload
  match 'songs' => 'songs#upload', :as => :upload
  match 'station_next#id' => 'stations#next_song', :as => :next_song
  resources :songs
  get 'connect', to: 'connections#create', as: 'connect'
  get 'disconnect', to: 'connections#destroy', as: 'disconnect'
		
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://bandleader.org/">Bandleader</a>
    by Michael Dorman
  </small>
  <nav>
    <ul>
		<li><%= link_to "About", about_path %></li> 
		<li> <%= link_to "Contact", contact_path %></li> 
		<li> <a href="">News</a></li> 
		</ul> 
		</nav> 	
</footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
			<%= link_to "bandleader", root_path, id: "logo" %> 
			<nav> 

  
				<ul class="nav pull-right"> 
				  	 <% if session[:user_id] %>
						<li> <%= link_to "Stations", stations_url %></li> 
    				  <li><%= link_to current_user.username, current_user %></li>
  					  <li><%= link_to "Log out", logout_path %></li> 
 					 <% else %>
 					 <li> <%= link_to "Home", root_path %></li> 
  					 <li><%= link_to "Sign up", signup_path %></li>
   					 <li><%= link_to "log in", login_path %></li> 
  					<% end %>
					<li> <%= link_to "Help", help_path %></li> 
				</ul> 
			</nav>
		</div> 
	</div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= stylesheet_link_tag "jplayer.blue.monday", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body class="<%= @home_page ? 'homepage' : ''%>">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
     <%= render 'layouts/footer' %>
    </div>
  </body>
  
</html>